name: ACM UCR Website
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run check
  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run eslint
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.14.2"
      - run: npm ci
      - run: npm run build
    env:
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{NEXT_PUBLIC_FIREBASE_API_KEY}}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
        { { NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET } }
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
        { { NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID } }
      NEXT_PUBLIC_FIREBASE_APP_ID: { { NEXT_PUBLIC_FIREBASE_APP_ID } }
      NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL:
        { { NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL } }
      NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: { { NEXT_PUBLIC_FIREBASE_PRIVATE_KEY } }
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: { { NEXT_PUBLIC_GOOGLE_CLIENT_ID } }
      NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: { { NEXT_PUBLIC_GOOGLE_CLIENT_SECRET } }
      NEXTAUTH_SECRET: { { NEXTAUTH_SECRET } }
      NEXTAUTH_URL: { { NEXTAUTH_URL } }
